.\" Manpage for jetfuel.
.\" Contact pete.romano@yahoo.com to correct errors or typos.
.TH man 1 "21 September 2012" "0.2.x" "jetfuel man page"
.SH NAME
jetfuel \- binary into jetfuel engine
.SH SYNOPSIS
jetfuel [TASK]
.SH DESCRIPTION
jetfuel(1) is currently a facade for grunt(1), with an added installer script.
.SH OPTIONS
jetfuel offloads most of its options to grunt(1)
.SH SEE ALSO
grunt(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Pete Romano (pete.romano@yahoo.com)